#! /usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR="$DIR/../build"
mkdir -p "$BUILD_DIR/build"
cmake -B$BUILD_DIR -H$DIR/.. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=TRUE
cmake --build $BUILD_DIR -- -j2
$BUILD_DIR/unit_tests
